<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popin</name>
   <tag></tag>
   <elementGuidId>b93b98a3-a639-4881-95e4-40880da762db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.messagePopupContent</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
