<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_search</name>
   <tag></tag>
   <elementGuidId>43516fdd-8bd4-4ca1-bbd5-467bb7582e12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[id=search-icon-legacy]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
