<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>channel_object</name>
   <tag></tag>
   <elementGuidId>52999167-fc50-483a-a889-8efc6f2bee0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>css=ytd-channel-renderer.style-scope.ytd-item-section-renderer</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
