<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>video_object</name>
   <tag></tag>
   <elementGuidId>69fadd37-ad54-4943-a59a-b770910163b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>css=ytd-video-renderer.style-scope.ytd-item-section-renderer</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
