<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ytp-menuitem-toggle-checkb</name>
   <tag></tag>
   <elementGuidId>2fedcb8a-8ca4-4961-ae67-33f177d830c9</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ytp-menuitem-toggle-checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ytp-id-17&quot;)/div[@class=&quot;ytp-panel&quot;]/div[@class=&quot;ytp-panel-menu&quot;]/div[@class=&quot;ytp-menuitem&quot;]/div[@class=&quot;ytp-menuitem-content&quot;]/div[@class=&quot;ytp-menuitem-toggle-checkbox&quot;]</value>
   </webElementProperties>
</WebElementEntity>
