<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Smoke test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2018-09-24T12:06:27</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f44ebbdf-a714-4543-bb0c-5dbcb0b50979</testSuiteGuid>
   <testCaseLink>
      <guid>36b8439b-1e30-4156-92d5-4bacac970c4d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/VOD/Functional Test/Smoke Test/PC/09.03.02.02 Texte pour un utilisateur Desktop</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9e7024d-ef5f-424a-b4e8-cdd5dcc78221</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab5e772a-1940-4de7-bdf9-d1ee0da93ba8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5511d08f-9187-4977-8ed1-84aa96f52355</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac1e72f1-81f9-4627-a770-de8570254195</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84e0268c-8da3-44f3-87f4-4aaf4fad0064</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>87d7673e-bfac-4f0f-a1da-5edbd905c548</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/VOD/Functional Test/Smoke Test/PC/13.01.Structure du player</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>e33c9f19-0a9a-48b2-bc62-8eefcce9d48b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/VOD/Functional Test/Smoke Test/PC/13.06.06 Avance et retour rapides</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
